# Generated by Django 6.0.6 on 2026-06-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_alter_report_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("REPORTED", "Reported"),
                    ("VERIFIED", "Verified"),
                    ("IN_PROGRESS", "In Progress"),
                    ("RESOLVED", "Resolved"),
                ],
                default="REPORTED",
                max_length=20,
            ),
        ),
    ]
